
auth.token=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

defaults.org=binaa
defaults.project=binaa

defaults.url=https://sentry.io/
