
auth.token=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

defaults.org=binaa
defaults.project=binaa

defaults.url=https://sentry.io/
