export enum Paths {
  AccessibilitySettings = 'AccessibilitySettings',
  Auth = 'Auth',
  ForgotPassword = 'ForgotPassword',
  LIBRARY_SCREEN='LIBRARY_SCREEN',
  Login = 'Login',
  Main = 'Main',
  Menu = 'Menu',
  PDF = 'PDF',
  Program = 'Program',
  Programs = 'Programs',
  SignUp = 'SignUp',
  Startup = 'Startup',
  Subscription = 'Subscription',
  TabNav = 'TabNav',
  TodayLessons = 'TodayLessons',
}
